"""updating username column

Revision ID: 9d76d3f0356b
Revises: 36047c1d0ebc
Create Date: 2024-10-04 08:35:09.696136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d76d3f0356b'
down_revision = '36047c1d0ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('messages', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
